export const enum Paths {
  USER_TABS = 'USER_TABS',
  MERCHANT_TABS = 'MERCHANT_TABS',
  LOGIN = 'LOGIN',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  SIGNUP_MERCHANT = 'SIGNUP_MERCHANT',
  SIGNUP_USER = 'SIGNUP_USER',
  SIGNUP_CHOOSE_ROLE = 'SIGNUP_CHOOSE_ROLE',
  SIGNUP_MERCHANT_SUCCESS = 'SIGNUP_MERCHANT_SUCCESS',
  CONFIRM_EMAIL = 'CONFIRM_EMAIL',
  STORE = 'STORE',
  SCAN_STORE = 'SCAN_STORE',
  QR_SCANNER = 'QR_SCANNER',
  MERCHANT_QR_PAYMENT = 'MERCHANT_QR_PAYMENT',
  PROFILE = 'PROFILE',
  QR_CODE = 'QR_CODE',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',
  SET_MERCHANT_PASSWORD = 'SET_MERCHANT_PASSWORD',
  CREATE_PROGRAM = 'CREATE_PROGRAM',
}

export const enum UserTabPaths {
  MY_STORES = 'MY_STORES',
  DISCOVER = 'DISCOVER',
  WALLET = 'WALLET',
  EXPENSES = 'EXPENSES',
}

export const enum MerchantTabPaths {
  PROGRAM = 'PROGRAM',
  CUSTOMERS = 'CUSTOMERS',
  BUSINESS = 'BUSINESS',
  BALANCE = 'BALANCE',
  REQUEST = 'REQUEST',
}
