export const enum Paths {
  USER_TABS = 'USER_TABS',
  MERCHANT_TABS = 'MERCHANT_TABS',
  LOGIN = 'LOGIN',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  CONFIRM_FORGOT_PASSWORD = 'CONFIRM_FORGOT_PASSWORD',
  SET_NEW_PASSWORD = 'SET_NEW_PASSWORD',
  SIGNUP_MERCHANT = 'SIGNUP_MERCHANT',
  SIGNUP_USER = 'SIGNUP_USER',
  CHOOSE_ROLE = 'CHOOSE_ROLE',
  SIGNUP_MERCHANT_SUCCESS = 'SIGNUP_MERCHANT_SUCCESS',
  CONFIRM_EMAIL = 'CONFIRM_EMAIL',
  STORE = 'STORE',
  TOP_UP_STORE = 'TOP_UP_STORE',
  QR_SCANNER = 'QR_SCANNER',
  SCAN_USER = 'SCAN_USER',
  CREDIT_POINTS = 'CREDIT_POINTS',
  REQUEST_POINTS = 'REQUEST_POINTS',
  PROFILE = 'PROFILE',
  QR_CODE = 'QR_CODE',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',
  SET_MERCHANT_PASSWORD = 'SET_MERCHANT_PASSWORD',
  CREATE_PROGRAM = 'CREATE_PROGRAM',
  TOP_UP_PROGRAM = 'TOP_UP_PROGRAM',
  EDIT_PROGRAM = 'EDIT_PROGRAM',
  PROGRAM_DETAILS = 'PROGRAM_DETAILS',
  EDIT_BUSINESS = 'EDIT_BUSINESS',
}

export const enum UserTabPaths {
  MY_STORES = 'MY_STORES',
  DISCOVER = 'DISCOVER',
  WALLET = 'WALLET',
  EXPENSES = 'EXPENSES',
}

export const enum MerchantTabPaths {
  PROGRAM = 'PROGRAM',
  CUSTOMERS = 'CUSTOMERS',
  BUSINESS = 'BUSINESS',
  BALANCE = 'BALANCE',
  REQUEST = 'REQUEST',
}
